name: "Automated Build"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: oven-sh/setup-bun@9b21598af8d4dfc302e5a30250007de0fda92acc # v1
        with:
          bun-version: 1.0.1

      - name: Cache node_modules
        id: cache-npm-packages
        uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
        env:
          cache-name: cache-node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('bun.lockb') }}

      - name: Install Dependencies
        if: ${{ steps.cache-npm-packages.outputs.cache-hit != 'true' }}
        run: bun install

      - name: Build
        run: bun run build

      - name: Commit & Push changes
        uses: actions-js/push@156f2b10c3aa000c44dbe75ea7018f32ae999772
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Update dist/index.js; ${{ github.event.head_commit.message }}
          branch: dist
          force: true
